In [61]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [62]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df =  application_df.drop(columns=['EIN', 'NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [63]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [64]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [65]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 15

# Identify application types to be replaced
application_types_to_replace = application_df['APPLICATION_TYPE'].value_counts()[application_df['APPLICATION_TYPE'].value_counts() < cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
T12         27
T2          16
Other       11
Name: APPLICATION_TYPE, dtype: int64

In [66]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [67]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [68]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 2
classifications_to_replace = application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
Other       26
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
C1238       10
C1278       10
C1237        9
C1235        9
C7210        7
C1720        6
C2400        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C1267        2
C1256        2
C1234        2
C1246        2
C3200        2
Name: CLASSIFICATION, dtype: int64

In [69]:
# Convert categorical data to numeric with `pd.get_dummies`
categorical_features = application_df.dtypes[application_df.dtypes == 'object'].index.tolist()

encoded_categorical_data = pd.get_dummies(application_df[categorical_features])

In [70]:
# add the new columns and remove the old ones
application_df = pd.concat([application_df, encoded_categorical_data], axis=1)
application_df.drop(columns=categorical_features, inplace=True)

application_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T3,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,0

In [71]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop(columns=['IS_SUCCESSFUL']).values
y = application_df['IS_SUCCESSFUL'].values
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [72]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [73]:
# Increased nodes per layer, switched the activation function in the second layer to a tanh isntead of a relu
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 120
hidden_nodes_layer2 = 60
hidden_nodes_layer3 = 40

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="tanh")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_40 (Dense)            (None, 120)               10560

 dense_41 (Dense)            (None, 60)                7260

 dense_42 (Dense)            (None, 40)                2440

 dense_43 (Dense)            (None, 1)                 41

=================================================================
Total params: 20301 (79.30 KB)
Trainable params: 20301 (79.30 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [74]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [75]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=125)

Epoch 1/125
804/804 [==============================] - 3s 2ms/step - loss: 0.5650 - accuracy: 0.7220
Epoch 2/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5527 - accuracy: 0.7301
Epoch 3/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5506 - accuracy: 0.7308
Epoch 4/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5475 - accuracy: 0.7327
Epoch 5/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5469 - accuracy: 0.7322
Epoch 6/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7355
Epoch 7/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7346
Epoch 8/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5440 - accuracy: 0.7345
Epoch 9/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7358
Epoch 10/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5428 - accuracy: 0.7358
Epoch 11/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7356
Epoch 12/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7361
Epoch 13/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7371
Epoch 14/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7372
Epoch 15/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7376
Epoch 16/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5389 - accuracy: 0.7374
Epoch 17/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5383 - accuracy: 0.7386
Epoch 18/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7392
Epoch 19/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7389
Epoch 20/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7392
Epoch 21/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7396
Epoch 22/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7395
Epoch 23/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5355 - accuracy: 0.7399
Epoch 24/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7407
Epoch 25/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7401
Epoch 26/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7408
Epoch 27/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7404
Epoch 28/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7406
Epoch 29/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7414
Epoch 30/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5332 - accuracy: 0.7413
Epoch 31/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7404
Epoch 32/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7414
Epoch 33/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7406
Epoch 34/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7413
Epoch 35/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5314 - accuracy: 0.7419
Epoch 36/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5318 - accuracy: 0.7425
Epoch 37/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5317 - accuracy: 0.7420
Epoch 38/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5315 - accuracy: 0.7420
Epoch 39/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7417
Epoch 40/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5315 - accuracy: 0.7413
Epoch 41/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7423
Epoch 42/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5310 - accuracy: 0.7421
Epoch 43/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5309 - accuracy: 0.7416
Epoch 44/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5300 - accuracy: 0.7428
Epoch 45/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5304 - accuracy: 0.7426
Epoch 46/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5300 - accuracy: 0.7428
Epoch 47/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5303 - accuracy: 0.7428
Epoch 48/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7435
Epoch 49/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7439
Epoch 50/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5292 - accuracy: 0.7428
Epoch 51/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5292 - accuracy: 0.7430
Epoch 52/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5291 - accuracy: 0.7425
Epoch 53/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5289 - accuracy: 0.7432
Epoch 54/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7431
Epoch 55/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5287 - accuracy: 0.7429
Epoch 56/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5290 - accuracy: 0.7436
Epoch 57/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5284 - accuracy: 0.7427
Epoch 58/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5280 - accuracy: 0.7440
Epoch 59/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5279 - accuracy: 0.7432
Epoch 60/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5279 - accuracy: 0.7433
Epoch 61/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5279 - accuracy: 0.7435
Epoch 62/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5279 - accuracy: 0.7439
Epoch 63/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5274 - accuracy: 0.7438
Epoch 64/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5275 - accuracy: 0.7441
Epoch 65/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5271 - accuracy: 0.7436
Epoch 66/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5273 - accuracy: 0.7432
Epoch 67/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5270 - accuracy: 0.7442
Epoch 68/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5270 - accuracy: 0.7442
Epoch 69/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5270 - accuracy: 0.7436
Epoch 70/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5264 - accuracy: 0.7434
Epoch 71/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5265 - accuracy: 0.7440
Epoch 72/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5264 - accuracy: 0.7434
Epoch 73/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5267 - accuracy: 0.7435
Epoch 74/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5263 - accuracy: 0.7441
Epoch 75/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5267 - accuracy: 0.7441
Epoch 76/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5263 - accuracy: 0.7433
Epoch 77/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5260 - accuracy: 0.7440
Epoch 78/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5263 - accuracy: 0.7442
Epoch 79/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5262 - accuracy: 0.7441
Epoch 80/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5258 - accuracy: 0.7441
Epoch 81/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5257 - accuracy: 0.7437
Epoch 82/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5261 - accuracy: 0.7437
Epoch 83/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5255 - accuracy: 0.7442
Epoch 84/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5259 - accuracy: 0.7433
Epoch 85/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5255 - accuracy: 0.7444
Epoch 86/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5255 - accuracy: 0.7442
Epoch 87/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5255 - accuracy: 0.7438
Epoch 88/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5259 - accuracy: 0.7441
Epoch 89/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5254 - accuracy: 0.7439
Epoch 90/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5252 - accuracy: 0.7444
Epoch 91/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5249 - accuracy: 0.7445
Epoch 92/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5249 - accuracy: 0.7449
Epoch 93/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5253 - accuracy: 0.7442
Epoch 94/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5249 - accuracy: 0.7447
Epoch 95/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5249 - accuracy: 0.7443
Epoch 96/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7442
Epoch 97/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5251 - accuracy: 0.7434
Epoch 98/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5251 - accuracy: 0.7444
Epoch 99/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5255 - accuracy: 0.7442
Epoch 100/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7448
Epoch 101/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7449
Epoch 102/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5245 - accuracy: 0.7440
Epoch 103/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5246 - accuracy: 0.7447
Epoch 104/125
804/804 [==============================] - 3s 3ms/step - loss: 0.5254 - accuracy: 0.7448
Epoch 105/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5249 - accuracy: 0.7448
Epoch 106/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5250 - accuracy: 0.7440
Epoch 107/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5244 - accuracy: 0.7448
Epoch 108/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5244 - accuracy: 0.7440
Epoch 109/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5247 - accuracy: 0.7449
Epoch 110/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7444
Epoch 111/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5250 - accuracy: 0.7441
Epoch 112/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5242 - accuracy: 0.7444
Epoch 113/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5241 - accuracy: 0.7441
Epoch 114/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5240 - accuracy: 0.7444
Epoch 115/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5244 - accuracy: 0.7451
Epoch 116/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5238 - accuracy: 0.7453
Epoch 117/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5237 - accuracy: 0.7444
Epoch 118/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5242 - accuracy: 0.7444
Epoch 119/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5240 - accuracy: 0.7449
Epoch 120/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5244 - accuracy: 0.7439
Epoch 121/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5239 - accuracy: 0.7449
Epoch 122/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5238 - accuracy: 0.7445
Epoch 123/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5240 - accuracy: 0.7453
Epoch 124/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5239 - accuracy: 0.7447
Epoch 125/125
804/804 [==============================] - 2s 3ms/step - loss: 0.5233 - accuracy: 0.7452

In [76]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5975 - accuracy: 0.7301 - 521ms/epoch - 2ms/step
Loss: 0.5975324511528015, Accuracy: 0.7301457524299622

In [77]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimization.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(